### ISSUE TITLE
Miss dependency module

### ISSUE THREAD

**Issue by sunset1995** [IoTtalk/iottalk-gui#4]
I have to manually run `npm install jade` and `npm install babel-runtime` so that webpack can run properly.
Maybe somethins is missing in your _package.json_

**Comment by iblislin** [comment]
The project jade had been renamed to `pug`. We listed it [here](https://github.com/IoTtalk/iottalk-gui/blob/master/app/package.json#L20) already.

For the `babel-runtime`, I will add it later.
